<?php

namespace AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findComments()
    {
        $qb = $this->createQueryBuilder('c');
        $qb
            ->addSelect('c.title')
            ->addSelect('c.username')
            ->addSelect('c.comment')
            ->addSelect('c.dateCreated')
            ->addOrderBy('c.dateCreated', 'DESC')
            ->setParameter('number', 20);


        $query = $qb->getQuery();
    }
}
