<?php

namespace AppBundle\Repository;

/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteMovieRepository extends \Doctrine\ORM\EntityRepository
{
    public function rateMovie()
    {
        $qb = $this->createQueryBuilder('r');
        $qb
            ->addSelect('r.rate');


        $query = $qb->getQuery();
    }
}
