<?php

namespace AppBundle\Repository;

/**
 * WatchlistItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WatchlistItemRepository extends \Doctrine\ORM\EntityRepository
{




}
